[[redirects]]
  from = "https://psnhackclub.netlify.app/"
  to = "https://psn.hackclub.com/:splat"
  status = 301

  [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://psnhackclub.netlify.app"
